[package]
name = "mini_mito"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "^58.3.0"
arrow-schema = "^58.3.0"
datafusion = "54.0.0"
futures = "0.3.33"
parquet = "^58.3.0"
rand = "0.10.2"
serde = {version = "=1.0.228", features = ["derive"]}
serde_json = "1.0.150"
tokio = {version = "1.53.1", features = ["rt-multi-thread", "macros"]}
tempfile = "3.27.0"
base64 = "0.22.1"
crc32fast = "1.5.1"

[dev-dependencies]
criterion = {version = "0.8.2", features = ["html_reports", "async_tokio"]}

[lib]
bench = false

[[bin]]
name = "mini_mito"
path = "src/main.rs"
bench = false

[[bench]]
name = "wal_bench"
harness = false

[[bench]]
name = "sstable_bench"
harness = false

[[bench]]
name = "memtable_bench"
harness = false

[[bench]]
name = "query_bench"
harness = false

[[bench]]
name = "throughput_bench"
harness = false
